### ISSUE TITLE
How to incorporate part of bedtools2 (under GPLv2) into a project under GPLv3+?

### ISSUE THREAD

**Issue by timflutre** [arq5x/bedtools2#10]
Hello,

I am developing a C++ package doing eQTL detection and I licensed it under GPLv3+ (the "+" meaning "or any later version"). By looking at the README.md or the source code (say "bedFile.h"), bedtools is licensed under GPLv2. Thus, I can't use code from bedtools2 into my package, see [here](http://programmers.stackexchange.com/a/167466).

Maybe you could switch to GPLv3+. But I can understand that you want to keep GPLv2, as switching can disrupt things for other developers. However, would it be possible to unambiguously specify in bedtools2 that you allow usage of the code under GPLv2 _as well as later versions_? That is, to switch to GPLv2+?

In fact, this is suggested in the LICENSE file itself, in [section 9](https://github.com/arq5x/bedtools2/blob/master/LICENSE#L237). Practically, this would require adding "or any later version" in the README.md file (and also in the header of the source files, to avoid confusion).

Thanks,
Tim

**Comment by diekhans** [comment]
Has any more thought been put into changing the license or dual licensing?  Leaving politics out of it, GPL is very problematic for those of us work in an environment that is not strictly GPL.   This very much impacts those of us in academic research groups who have to deal with software with multiple open source licenses.   Those who actually believe one should honor license are stuck with trying to figure out a project is derivative.  Many just ignore the license and release software that could be seen as `derived' from GPL-ed code under other licenses.

It seems many developers believe GPL forces commercial entities to `give back' to the community.  This is true when the commercial entity is in the business of selling software.  However, biotechs that take open source software, modify it, and then make tons of money off of some drug they develop are not required to give anything back.

It would make the life of many of us in open source bioinformatics a lot easier if great package like bedtools, especially those with libraries, had non-viral license.  While Apache seems to become very popular, even LGPL is fine, since the goal is to do research and make source available, not fight licensing battles.

**Comment by arq5x** [comment]
Planning to move to MIT this summer.

**Comment by awz** [comment]
Were you ever able to revisit this?   Apache 2 provides more certainty around software patents (which is appreciated by many.) MIT would address incompatibility with more licenses without the patent certainty, unfortunately.

**Comment by arq5x** [comment]
MIT license now.
