### ISSUE TITLE
bedtools groupby could not generate correct results.

### ISSUE THREAD

**Issue by ccmeth** [arq5x/bedtools2#1003]
Hi,
Thanks a lot for providing such a powerful tool. Recently I used the "bedtools groupby", however, I noticed that different results were generated in two devices and only one is correct. The version of these two devices is both v2.26.0 and one is ubuntu and the other is centos. The command I used is "bedtools groupby -i tmp3.bed -g 1 -c 2,3 -o collapse".

![image](https://user-images.githubusercontent.com/54224100/172805711-1ce165fa-b7b7-4ef5-826d-78b3ee5db96c.png)

![image](https://user-images.githubusercontent.com/54224100/172805853-05b00df3-0b8b-49c1-ad9a-c33866642b47.png)

![image](https://user-images.githubusercontent.com/54224100/172805939-c29371ec-de5b-41e4-b3ee-07e1885d66ba.png)
 
Could you please tell me the possible reason behind this phenomenon?
Thank you!

**Comment by arq5x** [comment]
That would be explained by an autocomplete package being installed on one system and not the other: this is independent of bedtools itself. I am not sure of the cause, but would recommend installing the latest version of bedtools as bugs to groupby have been resolved since the version you are using.
