### ISSUE TITLE
Segmentation fault in merging VCF in v2.23

### ISSUE THREAD

**Issue by pelagial** [arq5x/bedtools2#208]
Hi,

I just upgraded from 2.19 to 2.23 and encountered a segmentation fault with bedtools merge applying to VCF files. Even with the small files shown below. 
I tested some other versions and the error appears from version 2.21 onwards.
The command is: bedtools merge  -d <distance> -i file.vcf

```bash
##fileformat=VCFv4.0
##source=RetroSeq v1.41
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=MEINFO,Number=1,Type=String,Description="Mobile element info of the form NAME,START,END,POLARITY">
##ALT=<ID=INS:ME,Type=String,Description="Insertion of a mobile element">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype quality">
##FORMAT=<ID=SP,Number=1,Type=Float,Description="Number of correctly mapped read pairs spanning breakpoint, useful for estimation of size of insertion">

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE18
scaffold1       40672   .       T       <INS:ME>        22      .       MEINFO=SINE;NOT_VALIDATED;SVTYPE=INS    GT:GQ:FL:SP     1/1:22:8:0
scaffold1       53847   .       T       <INS:ME>        27      .       MEINFO=SINE;NOT_VALIDATED;SVTYPE=INS    GT:GQ:FL:SP     0/1:27:7:0
scaffold1       65423   .       A       <INS:ME>        28      .       MEINFO=SINE;NOT_VALIDATED;SVTYPE=INS    GT:GQ:FL:SP     1/1:28:8:0
```
BED files work fine though. Has that happened to someone else, or am I doing something wrong here?

Thanks,
Fritjof

**Comment by nkindlon** [comment]
Hi Fritjof, thanks for reporting this. I'll look into it immediately.

**Comment by nkindlon** [comment]
Hi again, I found the problem, but there is some confusion that perhaps you could help us with. 
Earlier versions did not break because there was a different bug, such that we weren't processing imprecise / structural variants correctly. When the ALT field is enclosed in angle brackets, '<' '>', we were only using the length of the string in the ALT field to calculate the length of the variation, as is done with precise variants. Now, when we see those brackets, we parse the INFO field for the tag "SVLEN=", and use the number after it for the actual length. It was our understanding that this tag is required, and yours is the first we've encountered that does not contain it since the fix.The file specification is somewhat unclear; it mentions the "SVLEN=" tag, and shows it in the examples, but doesn't state it is explicitly required, as far as I can see.
https://samtools.github.io/hts-specs/VCFv4.2.pdf
 Do you know whether the tag is required? If not, any suggestions on how to determine the length? I'm still looking around on other forums for this. Thanks.
-Neil

**Comment by nkindlon** [comment]
On further review, it seems the SVLEN= tag is in fact not required. However, without it, there is no accurate way to determine the length of the variation. So, what we'll do is emit a warning to stderr, treat it as length 1, which may not be biologically accurate, and continue. Thus your output will look like this:
WARNING: line number 1 of file data/file.vcf has an imprecise variant, but no SVLEN specified. Defaulting to length 1.
WARNING: line number 2 of file data/file.vcf has an imprecise variant, but no SVLEN specified. Defaulting to length 1.
WARNING: line number 3 of file data/file.vcf has an imprecise variant, but no SVLEN specified. Defaulting to length 1.
scaffold        40671   40672
scaffold1       53846   53847
scaffold1       65422   65423

**Comment by pelagial** [comment]
Hi Neil,

sorry for the late reply and thanks for looking into the case.  Indeed, RetroSeq (the SV caller) does not report the length, because that is difficult to do for non-reference insertions. I initially assumed that the POS-field (i.e. the SV breakpoint) was taken for merging, so I guess your fix is suitable for this case. I will test it on my data soon!

Best

Fritjof

**Comment by nkindlon** [comment]
Ok, thanks, Fritjof. Please let us know if there are any other issues. 
Thanks,
-Neil

**Comment by eroller** [comment]
Hi guys, do you really need to know the difference in length between ref and alt or is it sufficient to just know the reference length covered? If you just need the reference length why not use END to determine that? It is present since VCF 4.1:

END : end position of the variant described in this record (for use with symbolic alleles)

**Comment by eroller** [comment]
related issue: https://github.com/arq5x/bedtools2/issues/316
