### ISSUE TITLE
bedtools closest: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by retrogenomics** [arq5x/bedtools2#253]
Dear Aaron,

I recently migrated from bedtools v2.20.1 to bedtools v2.23.0, and I noticed a potential bug using bedtools closest with -header option:

a.bed
#chr	start	stop	name	score	strand
chr1	10000	20000	gene1	50	-

b.bed
chr1	21000	22000	region1	50	-

with v2.20.1,
bedtools closest -a a.bed -b b.bed -s -D a -id -header
returns:
#chr	start	stop	name	score	strand
chr1	10000	20000	gene1	50	-	chr1	21000	22000	region1	50	-	-1001

bedtools closest -a a.bed -b b.bed -s -D a -id
returns:
chr1	10000	20000	gene1	50	-	chr1	21000	22000	region1	50	-	-1001

but with v2.23.0,
bedtools closest -a a.bed -b b.bed -s -D a -id -header
returns:
Segmentation fault (core dumped)

bedtools closest -a a.bed -b b.bed -s -D a -id 
returns:
chr1	10000	20000	gene1	50	-	chr1	21000	22000	region1	50	-	-1001

-Gael

**Comment by retrogenomics** [comment]
Hi
I just realize that v2.24.0 was released. I tried it with this new version and the error disappeared, and it's now working like a charm. However, since nothing related to this issue was indicated in the 2.24 release description, I am wondering if the bug was actually fixed or whether my example is not able to catch it anymore.
-Gael

**Comment by nkindlon** [comment]
I'll look into this also. I also don't recall offhand any changes since 2.23 that might have caused this, but there were many small ones since then, so there may have been one too minor for the release notes or that was simply forgotten.

**Comment by nkindlon** [comment]
Ok, yes, I get the same results, and there were indeed two changes to explain it. One minor, one major:

2.23 does have a bug, in that it doesn't check for the header in closest until the end. At that point, it tries to ask the fileReader for it, but said fileReader has already been destroyed.

In 2.24, it correctly asks for the header at the beginning. That's the minor change. The major one is that I did a significant refactor of all tools to make them APIs. (The goal was that eventually, other developers could use these APIs in their own software programs, rather than be forced to only call our programs from the command line). One effect of this is that tools destroyed before the context, which contains the file readers, so even if closest had asked for the header at the end, it still wouldn't seg fault.

But thanks again for your scrutiny. It's hard for us to test all the different combinations of output options, so it's good to know this one is covered now.

**Comment by arq5x** [comment]
Sorry, I lost track - is this resolved in pull request #247 ?

**Comment by nkindlon** [comment]
This was actually resolved in release 2.24 and can be closed now.

**Comment by arq5x** [comment]
Gotcha - thanks Neil.
