### ISSUE TITLE
bedtools merge -s missing output

### ISSUE THREAD

**Issue by retrogenomics** [arq5x/bedtools2#254]
Hi,
In bedtools v2.24.0, when I use bedtools merge with -s option using a file which contains more than 6 columns (BED6 and extra-custom columns), the output is empty. This was not happening with previous versions of bedtools (v2.20.1) or when removing the -s option.
-Gael

**Comment by arq5x** [comment]
Thanks for reporting this. Can you provide a minimal example of your input file? This will help us test and the bug.

**Comment by nkindlon** [comment]
Thanks Gael. I'll make a small sample file and look into this. In the meantime, if you have an example input file, you can send it to me at nek3d@virginia.edu.
-Neil

**Comment by retrogenomics** [comment]
Thanks for your quick answer. Here are some examples:
$ cat c.bed
#chr	start	stop	name	score	strand
chr1	10000	20000	gene1	50	+
chr1	20100	25000	gene2	100	+

$ cat d.bed
#chr	start	stop	name	score	strand	remark
chr1	10000	20000	gene1	50	+	foo
chr1	20100	25000	gene2	100	+	bar

$ ~/.local/bin/bedtools-2.24.0/bedtools merge -d 200 -s -i c.bed
chr1	10000	25000

$ ~/.local/bin/bedtools-2.24.0/bedtools merge -d 200 -s -i d.bed
nothing outputted

~/.local/bin/bedtools-2.24.0/bedtools merge -d 200 -i d.bed
chr1	10000	25000

-Gael

**Comment by nkindlon** [comment]
Great, thanks! I will take a look.

**Comment by nkindlon** [comment]
Ok, I see what happened. Because you added a 7th field, the records in d.bed are considered what we call "BedPlus". I originally wrote those with the impression that all of the first six fields are still required, but recently learned that only the first 3 are, and had to change it accordingly for another bug. Since strands are then not required, a bedplus is assumed not to have them, and marks their strands unknown. Stranded merge then ignores them entirely, and you get no output. 

So what I'll do is change it such that BedPlus only needs the first 3 fields fixed, but if it happens to have more, and the 6th is a strand, it will set it's strand field.

**Comment by nkindlon** [comment]
Ok, all set. It now gives the correct output. Also, I noticed that stranded merge never output the strand by default. The user had to -c 6 -o distinct if the strand was in column 6. I changed it so the strand is printed now. 
Completed in pull request #247.

**Comment by retrogenomics** [comment]
Great thanks !
