### ISSUE TITLE
Memory leak in groupby in v2.25.0

### ISSUE THREAD

**Issue by chapmanb** [arq5x/bedtools2#303]
Aaron and Neil;
I'm running into an apparent memory leak with bedtools groupby in v2.25.0.  When running groupby like:
```
cat input.bed | bedtools groupby -prec 21 -g 1,5 -c 1,2,3,5 -o first,first,max,first
```
on a large input file like:
```
chr1	0	10029	0	NO_COVERAGE
chr1	10029	10031	1	LOW_COVERAGE
chr1	10031	10035	2	LOW_COVERAGE
chr1	10035	10038	4	CALLABLE
chr1	10038	10069	5	CALLABLE
chr1	10069	10070	3	LOW_COVERAGE
chr1	10070	10077	5	CALLABLE
chr1	10077	10080	4	CALLABLE
chr1	10080	10081	6	CALLABLE
chr1	10081	10118	7	CALLABLE
```
Memory steadily increases the longer it runs, making it look like a straight up leak. I'm doing this across chromosomes so it ends up filling up all available memory on the larger ones.

This appears to be separate from arq5x/bedtools2#302 since that doesn't fix the issue. v2.24.0 works on this with same input without using much memory at all.

Please let me know if any other information at all would help to reproduce the problem. Thanks much.

**Comment by arq5x** [comment]
Thanks Brad, it looks like there are multiple issues with groupby at the moment subsequent to the recent refactoring. I will try to dig into this in the next few days. Sorry for the trouble.

**Comment by nkindlon** [comment]
Hi guys,
   Aaron, I only got to take a quick look but I think I see the cause of the memory growth. In groupBy::findNext, the while loop keeps getting more records until canGroup returns false. But in cleanupHits, only the first of these is actually deleted. The 2nd line, hits.clearAll(), is a bit of a misnomer in that it only erases the pointers. The rest of the actual records will stay in the FileRecordMgr's buffer until the program ends and the FRM is destroyed. Since it does get destroyed at the very end, profiling tools won't show it as a memory leak, since it technically isn't. 
   The cleanupHits logic was intended for sorted intersect and the like, where you want the DB hits to stay in the cache even when you're done with that query record. I must have hastily copied it over. Sorry about that. I think if you just change groupBy::cleanupHits to loop through all the hits and delete them individually, then call clearAll, it should be fine. (We could alternately overload FileRecordMgr::deleteRecord to take the whole RecordKeyVector and do this.)
