### ISSUE TITLE
bedtools coverage memory leak

### ISSUE THREAD

**Issue by guillermomarco** [arq5x/bedtools2#304]
I'm using bedtools coverage with bed and bam files:

```bedtools coverage -a file.bed -b test.bam```

I'm experiencing huge memory consumption (more than 30Gb + 16Gb of swap) for big bam files. I've tested it on bedtools 2.24 and 2.25. It's like its loading whole BAM into memory. Didn't have this problem in 2.23 (memory consumption varied depending on BAM size but not the point to eat all my ram memory)

I've tried to workaround this problem with ```-iobuff``` and ```-nobuf```. None of them seem to reduce memory usage.

**Comment by arq5x** [comment]
Have you tried using the -sorted option? Without -sorted, your BAM file will be loaded in an R-Tree in memory.

**Comment by guillermomarco** [comment]
Ok using -sorted option I'm getting asked for a "genome" file since not all the chromosomes in BAM file are in bed file. What does this refers to reference genome FASTA file, FAI, DICT?

**Comment by s1437643** [comment]
Check near the bottom of the Bedtools webpage for a description of the 
genome file: 
http://bedtools.readthedocs.org/en/latest/content/general-usage.html

On 30/09/15 17:07, Guillermo Marco wrote:
>
> Ok using -sorted option I'm getting asked for a "genome" file since 
> not all the chromosomes in BAM file are in bed file. What does this 
> refers to reference genome FASTA file, FAI, DICT?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/arq5x/bedtools2/issues/304#issuecomment-144462625>.
>


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by s1437643** [comment]
Check near the bottom of the Bedtools webpage for a description of the genome file: http://bedtools.readthedocs.org/en/latest/content/general-usage.html

**Comment by guillermomarco** [comment]
I already checked that however I don't have any tool to build the specified genome fil.

**Comment by nkindlon** [comment]
Hi Guillermo, 
    Currently there isn't a tool (that I know of) to build genome files. Perhaps making one isn't a bad idea. What people do now is make their own with linux tools at the command line. Here is an example of one way to make one from a bam file:
samtools view -H test.bam | grep "^@SQ" | cut -f2,4 | sed 's/LN://g;s/SN://g'  > myGenomeFile.txt

If the above is unfamiliar, what it's doing is using samtools to view the bam in  sam format, which is human readable. The -H options says "only print the header block". Then we grep for only the @SQ lines because those have the chromosome info we want. The "^" symbol before the @SQ string tells grep the line must begin with that string. Sam is tab delimited, so now we can use the cut command to get just the fields we want. These are fields 2 and 4, which contain the name and length. Finally, the sed command replaces the "SN:" and "LN:" each with nothing, leaving strictly just the chromosome names and their length, separated by a tab, which is the required format for a genome file. Someone who is better with sed, awk, and regular expressions probably could tell you a simpler command. But I hope this helps.

**Comment by jmarshall** [comment]
FAI files are themselves suitable for use as bedtools genome files: they have some extra columns, but (last time I looked) bedtools is only interested in the first two columns and ignores the rest.  So `samtools faidx` is a tool to build a genome file given a FASTA file.

(Noting this in the documentation was the first bedtools patch I was ever going to send, but I still haven't got around to it! :smile:)

**Comment by guillermomarco** [comment]
Transformed faidx to genome file removing extra columns. 👍
