### ISSUE TITLE
Bedtools merge goes into infinite loop when reading empty file

### ISSUE THREAD

**Issue by sndrtj** [arq5x/bedtools2#305]
Well.. title says it all.

Steps to reproduce:

```
touch test
bedtools merge test > test.merged
```

This will hang forever. In stead, this should either fail, or preferably (in UNIX spirit) output nothing (empty file again).  

Or is this expected behaviour? 
Thanks.

**Comment by nkindlon** [comment]
Hi Sander, 
   Believe it or not, that is indeed the intended behavior. Since you didn't use the -i option, it is waiting for standard input. This will also occur if you give merge no arguments at all. Defaulting to stdin when the -i is missing was a frequent request that we implemented a while back to better match other linux tools' behavior.
-Neil

**Comment by jmarshall** [comment]
> `bedtools merge test > test.merged`

If it was really matching other Unix tools' behaviour, it would treat `test` here as the input file (as @sndrtj expected) rather than wanting a `-i` option to specify an input file name :smile:

As it's not using the `test` argument at all, it could diagnose it as a user error.  And in fact providing EOF on stdin produces a suitable error message:

    $ bedtools merge test > test.merged
    …hangs wanting to read something from stdin…
    ^D
    ***** ERROR: Unrecognized parameter: test *****
    $

It seems like moving the `cmdArgsValid()` check earlier would enable printing this error message without hanging forever first.

**Comment by sndrtj** [comment]
I have to agree with @jmarshall that this is not the way most Unix tools work. But nevertheless, my bad!
