### ISSUE TITLE
groupby seems to assume a BED-like input

### ISSUE THREAD

**Issue by arq5x** [arq5x/bedtools2#317]
https://groups.google.com/forum/#!topic/bedtools-discuss/7Q8T7-w978U

**Comment by nkindlon** [comment]
Added two fixes to pull request #294. 

The first is a specific fix for this this bug that stops the type checker from trying to parse strings with decimals as integers.

The 2nd is to override the file format for groupby if the input isn't bam. Since the type checker is what also establishes input and compression types - stdin/file/fifo/redirects and uncompressed/gzip/bgzip/bam, it couldn't be completely bypassed. But once it's finished, we can manually set the file type and record type to the NO_POS_PLUS_RECORD_TYPE. I left Bam as the exception, because you still want to treat bam as bam, of course.
