### ISSUE TITLE
failure to build from source with GCC6

### ISSUE THREAD

**Issue by mr-c** [arq5x/bedtools2#352]
Hello from the Debian-Med team,

While GCC 6 hasn't been released yet it will be the default compiler in the next release of Debian.

Recently a test compile was done of Bedrooms with GCC 6 and it sadly failed due to stricter type checking.

Lots of details are here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812294

Cheers,

**Comment by jmarshall** [comment]
The same failure occurs with `g++-5.1 -std=c++11`.  So the problem is not GCC 6 per se, but rather some additional `std::end()` templates that appear when you ask for C++11 or later (which GCC 6 does by default).

This could be hacked around by changing the code to e.g. `if (… || ((bed.end) < 0) )` (extra parentheses) or changing the name of the field (aargh), or probably the quite-a-lot-of-work good long-term fix would be to use `std::` where appropriate and nuke `using namespace std` — as this problem is a collision between `end` (from `using std::end`) and `end` (the class field).

Clang accepts this fine even with `-std=c++11`, so I suspect this may be a GCC parsing bug.  See <https://gcc.gnu.org/ml/gcc-help/2016-01/msg00085.html>.  However even if it is a bug, it has been around for a while and they might not fix it before GCC 6 ships with its C++14 default.  So bedtools may want to work around the problem nonetheless.

**Comment by arq5x** [comment]
Thanks very much for reporting this and John, thanks for the details. I will try to patch this up next week.

**Comment by arq5x** [comment]
Thanks you both for the help here. I think this should be addressed with commit 89cde77

**Comment by mr-c** [comment]
Good news, this was a [bug with GCC 6 after all](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=10200). 

If you want, the change at https://github.com/arq5x/bedtools2/commit/89cde770bab501574a7a22fe9ce75941584cedc4#diff-8d3d006144bb4e8409bd90ca7de1739fL789 can be reverted as it now compiles correctly with GCC 6 6-20160228-1

(Update courtesy of [Martin Michlmayr](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812294#19))

**Comment by jmarshall** [comment]
It seems fair to say that it was bedtools's test case that woke them up and got this GCC bug fixed. :smile:

However it's been around for years and reverting the change would mean that e.g. compiling bedtools with `g++-5.1 -std=c++11` would fail.  But then nobody noticed that before these GCC 6 prereleases, so maybe it doesn't matter…

**Comment by mr-c** [comment]
:-)

Whatever you want to do is fine by me

În Joi, 3 mar. 2016, 13:50 John Marshall, <notifications@github.com> a
scris:
