### ISSUE TITLE
Intersect BED with VCF with genotype data 

### ISSUE THREAD

**Issue by sigven** [arq5x/bedtools2#44]
After the 2.17 release I get an error when intersecting a BED file with a VCF that contains genotype information (i.e. sample VCF file)

In my query VCF, containing genotypes for 100 samples, I get the following error in 2.19 release:
intersectBed -a query.vcf.gz -b target.bed.gz -wa -wb
Error: line number 1 of file query.vcf.gz has 109 fields, but 10 were expected.

This worked fine in previous releases.

**Comment by silvia-s** [comment]
Hi,
I'm having the same sort of problem with bedtools version 2.24.0:

$ intersectBed -a test_119_lines.vcf.gz -b RepeatMasker_hg19_GRCh37.bed -wb > test_out.vcf
Error: line number 1 of file test_119_lines.vcf.gz has 12 fields, but 8 were expected.

The weird thing is that if I just add another line (variant) to the file, it works fine:
$ intersectBed -a test_120_lines.vcf.gz -b RepeatMasker_hg19_GRCh37.bed -wb > test_out.vcf

Or, if I simply unzip the .vcf file, it works fine as well:
$ bgzip -d test_119_lines.vcf.gz 
$ intersectBed -a test_119_lines.vcf -b RepeatMasker_hg19_GRCh37.bed -wb > test_out.vcf

Any idea why this happens?
Thanks!

**Comment by nkindlon** [comment]
Hi Silvia,
    Those are definitely odd results. In particular, unzipping the file should have no impact at all. Would you be able to send me the two files you mentioned at nek3d@virginia.edu? Thanks!
-Neil

**Comment by nkindlon** [comment]
Hi again Sylvia,
    Thanks for sending those files. I got all the exact same results you described above, which made no sense at all, until I simply re-zipped test_119_lines.vcf back into test_119_lines.vcf.gz, at which point the original command works fine with no error. Can you try that and see if it fixes your problem too?

 If it does, I think something just went wrong when it was zipped the first time. If that doesn't fix the problem, it's probably a hardware/OS/compiler version issue, which I'm afraid recent experience has shown us we're not equipped to help with.

**Comment by silvia-s** [comment]
Indeed, it works fine if I compress the file with gzip rather than with bgzip, but unfortunately I need to stick to bgzip as it is much faster than gzip for random access.

On the other hand, the bgzip version I'm using has not changed since ages and the bgzipped file works perfectly fine if I use an older version of bedtools (2.17.0).

Could you please check if this happens to you as well? If not, it must be some hardware/OS/compiler version issue as you said; if yes, I think it must be something related to how the latest bedtools version deals with bgzipped files...

Thank you!
Silvia

**Comment by nkindlon** [comment]
Oh I see. I missed the mention of bgzip vs gzip in the earlier conversation. You're right, using bgzip to uncompress and then recompress the file does not work. 
I'm out of the office today and tomorrow but I should be able to fix this on Monday.

**Comment by silvia-s** [comment]
Hi Neil,
Did you have any chance to have a closer look at the bgzip-linked bug?
Cheers,
Silvia

**Comment by jmarshall** [comment]
Bgzip maintainer here… I'd be interested to have a look, in case the problem is at the bgzip end.  I can't reproduce this with my small sample variants.vcf.gz file; could you email me your test_119_lines.vcf.gz test files too (jm18@sanger)?

What version of bgzip are you using?

**Comment by jmarshall** [comment]
Turns out Silvia has tested this with several different versions of bgzip, and in fact there's no problem with any of them.

The problem is in bedtools's `FileRecordTypeChecker::isTextDelimtedFormat()`, which doesn't allow for partially-read lines.  (The tokenizer keeps the incomplete last line despite `Tokenizer::IGNORE` being set.)  The test_119_lines.vcf.gz file has an amount of headers such that `isTextDelimtedFormat()` incorrectly decides the test file has 8 columns based on one incomplete data line (`MT  57  `…`HGNC|7495|Mt_t`).

**Comment by silvia-s** [comment]
Thanks for spotting the bug in bedtools, hope it will be fixed soon.

**Comment by nkindlon** [comment]
Hi, 
    I did find the same results John did and checked in a fix yesterday. It should appear in our next release. Thank you for your help and patience.
-Neil

**Comment by jmarshall** [comment]
@nkindlon: We were unaware of that, because there was no indication of it on this issue, or in **master** in this repository.

It'd be really useful if you could make a note on issues when you fix them.  Even if you only push it to your own fork, something like `Fixed #44` in the commit message makes GitHub automatically [add a note here](https://help.github.com/articles/closing-issues-via-commit-messages/).  Thanks!

**Comment by nkindlon** [comment]
Hi John,
      It wouldn't show up on master until Aaron's had time to review and merge them.  But you're right, I should have and usually do leave notes on bugs after pushing fixes. Things are a bit chaotic at the moment, as it's my last week with the lab and Aaron is out in Utah now, so, sorry if the service is irregular during the transition, and sorry you went through extra work.

**Comment by Amila1312** [comment]
Hi,

I have the same probleme as you "line number 1 of file s_sace_SNP_SCSU_ai.header.vcf has 10 fields, but 11 were expected" and I don't know what I should do to resolve this problem.

Which type of line have you add Silvia in your file ? 

Thanks

**Comment by silvia-s** [comment]
I haven't added any particular line, it was just a problem of bedtools handling files compressed with bgzip. If you instead use gzip or download the latest version of bedtools (updated 2 days ago), it should work fine.

Cheers

**Comment by tedtoal** [comment]
Hi, found this old thread, but I'm now having a similar issue with bedtools v2.26.0.  I am intersecting a .bed.gz zipped with gzip, with a regular .bed, and get the error message:

`Error: line number 10573710 of file x1.bed.gz has 4 fields, but 6 were expected.`

That line has 6 fields.

The file sizes are 113 Mb (.bed.zip) and 403Kb (.bed).  I can transfer them to you if you want.  

When I unzip the file with gunzip and feed it to bedtools stdin, it works without error.

**Comment by arq5x** [comment]
Hi @tedtoal - if this is also a problem on the latest version in the github repo, please send me the files (aaronquinlan@gmail.com)
