### ISSUE TITLE
Bedtools merge: Error with empty files and -c/-o option

### ISSUE THREAD

**Issue by christianbioinf** [arq5x/bedtools2#546]
There is some unexpected behaviour from ``bedtools merge`` (version 2.26.0) in case of empty files when using in combination with the options ``-c/-o``. I know that I could simply check if the file is empty before giving it to ``bedtools merge`` but I think the behaviour is not intended since without the option ``-c`` it works fine. Moreover, I am using it inside a large pipe so it would be cumbersome to always check the file if it is empty and then only execute ``bedtools merge`` in case of a non-empty file.
```
touch A.bed
bedtools merge -i A.bed -c 4 -o distinct
```
results in the following error
```
*****
***** ERROR: Requested column 4, but database file A.bed only has fields 1 - 0.
```
whereas
```
touch A.bed
bedtools merge -i A.bed
```
reports nothing (i.e. an empty file) which is the correct result.

**Comment by arq5x** [comment]
@nkindlon would you be able to have a look at this?

**Comment by johnpeden** [comment]
Hi @arq5x  @nkindlon 
This bug is still present in v2.30.0 it is triggered by any pipes that filters data to bedtools, if that filtering reduces the number of rows zero to triggers the error.

echo | bedtools sort | bedtools merge -c 4 -o sum > outfile.bed

*****
***** ERROR: Requested column 4, but database file - only has fields 1 - 0.

**Comment by arq5x** [comment]
Thanks @johnpeden, this is fixed in master and will be part of the next release.
