### ISSUE TITLE
bedtools closest with -fu/-fd does not return overlapping features

### ISSUE THREAD

**Issue by isthisthat** [arq5x/bedtools2#554]
Given a:

    chr1    1458885 1458886 .      0.902937412261963       +

and b:

    chr1    1455997 1458123 .       0       +
    chr1    1458279 1458890 .       0       +
    chr1    1458947 1459218 .       0       +

where there is an overlap with the middle interval in b, I would expect to get the same result whether or not I use `-fu`/`-fd` (unless `-io` was used). That is, the following three test cases should give me the same interval:

    bedtools closest -t first -s -a <(echo -e 'chr1\t1458885\t1458886\t.\t0.9\t+') -b <(echo -e 'chr1\t1455997\t1458123\t.\t0\t+\nchr1\t1458279\t1458890\t.\t0\t+\nchr1\t1458947\t1459218\t.\t0\t+')
    bedtools closest -t first -s -fu -D a -a <(echo -e 'chr1\t1458885\t1458886\t.\t0.9\t+') -b <(echo -e 'chr1\t1455997\t1458123\t.\t0\t+\nchr1\t1458279\t1458890\t.\t0\t+\nchr1\t1458947\t1459218\t.\t0\t+')
    bedtools closest -t first -s -fd -D a -a <(echo -e 'chr1\t1458885\t1458886\t.\t0.9\t+') -b <(echo -e 'chr1\t1455997\t1458123\t.\t0\t+\nchr1\t1458279\t1458890\t.\t0\t+\nchr1\t1458947\t1459218\t.\t0\t+')

But they don't:

    chr1    1458885 1458886 .      0.9       +       chr1    1458279 1458890 .       0       +
    chr1    1458885 1458886 .      0.9       +       chr1    1455997 1458123 .       0       +     -763
    chr1    1458885 1458886 .      0.9       +       chr1    1458947 1459218 .       0       +     62

Is this the expected behaviour or a bug? I could not find a way to make an upstream/downstream-specific comparison that allows for overlapping intervals.

**Comment by arq5x** [comment]
I am on the road for the next week. There was a bug related to this in version 2.26 that has been fixed in the current version on the Github repository. Would you mind cloning that and testing ?

**Comment by isthisthat** [comment]
Unfortunately the master branch still gives me the same result..

**Comment by arq5x** [comment]
Thanks for checking. I will hopefully get some time to dig into this over the weekend.

**Comment by isthisthat** [comment]
Thank you very much. I'm currently using a workaround where I run `closest` twice, once with `-fu`/`-fd` and once without and compare the distances. It seems to work ok for now.

**Comment by arq5x** [comment]
I just looked into this and feel that the result is correct, as 1) the first interval in B is upstream of A, the second interval in B overlaps A (see IGV image of your files), and the third interval in B is downstream of A.

Thus, the default execution should return the middle interval in B because it overlaps A. When using `-fu` and forcing it to return the closest upstream (non-overlapping) interval in A, it should return the first interval in B. Finally, when using `-fd` and forcing it to return the closest downstream (non-overlapping) interval in A, it should return the last interval in B.


![image](https://user-images.githubusercontent.com/72291/29236260-94c7f2f6-7ec5-11e7-8b54-44927f5dc86c.png)

**Comment by isthisthat** [comment]
Without getting into semantics of what's closest, I think it would be useful to have a way to specify upsteam/downstream but also include overlaps. Then using the existing `-io` option you could exclude overlaps if you wanted to. Otherwise there is no way to do the former in with a single command.
