### ISSUE TITLE
coverage: Error: Unable to open file -b. Exiting.

### ISSUE THREAD

**Issue by etiennemahe** [arq5x/bedtools2#652]
I'm trying to run bedtools coverage -hist as part of a larger unix script. While I am able to run the bedtools coverage -hist command on the files directly, when I run the script as a whole I get the following message:

Error: Unable to open file -b. Exiting.

Any ideas?

**Comment by mschilli87** [comment]
wild guess: Your file `-b` contains spaces and when you run on the comman line you tab-complete, so spaces get escaped by `\` but in your script you use a variable that you evaluate using `$` without wrapping it in `"`..`"`.
There are plenty of other possibilities but this is likely a bug in your shell script or otherwise unrelated to bedtools. I'd recomment stripping down your script into a minimal example and uploading that (incl. minimal test data) to a stackoverflow question and linking it here.
