### ISSUE TITLE
Empty links in documentation

### ISSUE THREAD

**Issue by cmdcolin** [arq5x/bedtools2#743]
All of these links are empty in the documentation it seems

https://bedtools.readthedocs.io/en/latest/content/tools/makewindows.html https://bedtools.readthedocs.io/en/latest/content/tools/bedpetobam.html https://bedtools.readthedocs.io/en/latest/content/tools/expand.html https://bedtools.readthedocs.io/en/latest/content/tools/igv.html https://bedtools.readthedocs.io/en/latest/content/tools/multiinter.html https://bedtools.readthedocs.io/en/latest/content/tools/nuc.html https://bedtools.readthedocs.io/en/latest/content/tools/pairtobed.html https://bedtools.readthedocs.io/en/latest/content/tools/tag.html

I found this because I wanted makewindows docs personally :)

**Comment by diekhans** [comment]
Any idea when this will actually be fixed???

 I am getting notes from collaborators that says they used " bedtools multiinter ... ", but no idea what this does

Great, I can guess (bad idea) or google around (lots of hits to empty doc).

Sady, bedtools is actually some of the better-documented bioinformatics software, when that documentation exists...

**Comment by arq5x** [comment]
Finally added.
https://bedtools.readthedocs.io/en/latest/content/tools/multiinter.html

**Comment by VenithaB** [comment]
Hi, just wanted to let you know that the documentation for everything except multiinter is still missing. Have these been deprecated?

**Comment by bentyeh** [comment]
Bumping this... would also like to see the documentation for these other tools added!

Running the programs without any arguments (or with a `-h` flag) will show usage options, but not a complete documentation.

(Some of these programs apparently used to have more complete documentation pages, like this one for `pairtobed`: https://bioweb.pasteur.fr/docs/modules/bedtools/2.17.0/content/pairToBed.html. Curious what happened to these pages...)

----

Update: seems like the documentation file for `pairtobed` was deleted in commit 0b66b22 (Dec 18, 2012), when bedtools was still at version 2.17.0? Commit histories for the files under `src/pairToBed/` indicate that the source code for `pairtobed` essentially hasn't changed since then...so why did the documentation get deleted?
