### ISSUE TITLE
question about bedtools getfasta

### ISSUE THREAD

**Issue by ljl000** [arq5x/bedtools2#784]
Hi,
when I use bedtools getfasta to extract DNA sequence from a genome sequence file, I got a Warning like this :Warning: the index file is older than the FASTA file. Should I just ignore this or what option do I need to performance.
Thanks!

**Comment by ljl000** [comment]
Well, I just sort it off.

**Comment by joelnitta** [comment]
From what I can tell, `bedtools` automatically creates an index file based on the fasta file before running (to make it more efficient, I suppose). So if you have `genome.fasta`, it will create `genome.fasta.fai` in the same directory. The problem is, if you then over-write your original fasta with a new `genome.fasta`, `bedtools` will still try to use the old `genome.fasta.fai`, which causes the error. The solution is to delete `genome.fasta.fai` first, then `bedtools` will generate a new index file, which will be in sync with the new fasta file.
