### ISSUE TITLE
SIGPIPE with bedtools intersect

### ISSUE THREAD

**Issue by nh13** [arq5x/bedtools2#824]
I am having an issue with a SIGPIPE signal being returned when piping into `bedtools intersect`, likely due to `stdin` not being fully read.  Likely an upstream process (in my case `bedtools merge`) is still trying to write, but `bedtools intersect` has detected that the two files no longer can intersect (ex. the B file has no more entries).

```bash
cat foo.bed bar.bed | bedtools merge | bedtools intersect -a stdin -b regions.bed -g genome.fasta.fai > /dev/null
```

It is fully reproducible on a test case I have, but I don't have the ability to share it (confidential).

I want to use `bedtools intersect` in a pipe chain, but this precludes me from doing so, and requires an extra file to be written.

**Comment by 38** [comment]
This should be expected behavior, since this is the POSIX's mechanism that saves the CPU when the consumer of the pipe is dead. 

I am not sure why this prevents you to do anything, as long as the intersect operation is done and the result is complete. 

Again `bedtools merge` killed by `SIGPIPE` is by design in POSIX API and UNIX system, nothing related to bedtools at all.

**Comment by nh13** [comment]
I am  y no means an expert, but if I use `set -o pipefail` I don’t expect `bedtools intersect` to fail if it actually succeeds successfully as part of a pipe chain. It sounds like SIGPIPE is more of a notification than an indication of failure, [but that could be argued both ways](http://gnu-bash.2382.n7.nabble.com/pipefail-with-SIGPIPE-EPIPE-td14984.html).

**Comment by 38** [comment]
This can't be argued actually. In fact, SIGPIPE is the only mechanism for notifying program the other side of pipe is closed. This is problem with how bash treats SIGPIPE, but a possible workround would be:

(yes || true) | head -n 1

instead of 

yes | head -n 1

This will prevent the first part from failing.

**Comment by nh13** [comment]
Thank-you this was really instructive and you didn’t have to explain. Much appreciated.
