### ISSUE TITLE
merge doesn't print strand

### ISSUE THREAD

**Issue by lpantano** [arq5x/bedtools2#98]
in previous version merge gives the strand in the results, but bed tools v2.20.1 doesn't.

is this a bug, or it was decided not to printed? because it would be really helpful to continue printing the strand.

thanks

**Comment by balwierz** [comment]
You should then update the online documentation.
It still says the strand is printed:
https://bedtools.readthedocs.org/en/latest/content/tools/merge.html?highlight=merge

**Comment by arq5x** [comment]
Good catch, thanks!

**Comment by cnluzon** [comment]
Sorry to reopen this, but I think it's very related. I **do get strand info printed** when I do a stranded merge, and I don't know if this is expected behavior or not, because according to the [latest version documentation] (https://bedtools.readthedocs.org/en/latest/content/tools/merge.html?highlight=merge) it shouldn't:

> The -s option will only merge intervals that are overlapping/bookended and are on the same strand.
> $ cat A.bed
> chr1  100  200   a1  1 +
> chr1  180  250   a2  2 +
> chr1  250  500   a3  3 -
chr1  501  1000  a4  4 +

> $ bedtools merge -i A.bed -s
> chr1  100  250
> chr1  501  1000
> chr1  250  500

But this is not the behavior I get. I **still get the strand**. I'm using version 2.25.0 currently up-to-date (10/20/2015).

Taking the very same file:
> $ cat A.bed
> chr1  100  200   a1  1 +
> chr1  180  250   a2  2 +
> chr1  250  500   a3  3 -
> chr1  501  1000  a4  4 +

> $ bedtools merge -i A.bed -s
> chr1	100	250	+
> chr1	250	500	-
> chr1	501	1000	+
> $  bedtools merge -i A.bed
> chr1	100	500
> chr1	501	1000

This is a problem to me because I want to generate a fasta file after merging, and strand field appears in the fourth position, which is supposed to be the name field in bed format, and it's the one taken by bedtools getfasta afterwards when using -name option. Makes me need workarounds to get the fasta header I need in my records.

Thanks in advance! :)

**Comment by sclan** [comment]
Same issue with the strandness option in v2.25 - the "-s" option prints out the strandness in the output file by default and it's always in the 4th column before the columns from the "-c" option append to the output.

Workaround: use awk to switch the 4th column to the 6th column.
bedtools merge -c 4,5 -o collapse,distinct -delim "," -s -i a.bed > b.bed
awk '{OFS="\t"; print $1,$2,$3,$5,$6,$4}' b.bed > final.bed
